#!/bin/bash

git add .

git commit -m "update before release"

git pull

if [ $? -ne 0 ]; then
  echo "git pull failed"
  exit 1
fi

mvn -P prod clean package

if [ $? -ne 0 ]; then
  echo "maven failed"
  exit 1
fi
  
if [ ! -f target/doitincloud.rdbcache.jar ]; then
  echo "target/doitincloud.rdbcache.jar not found!"
  exit 1
fi

mkdir target/doitincloud.rdbcache

cp target/doitincloud.rdbcache.jar target/doitincloud.rdbcache
cp license.md target/doitincloud.rdbcache
cp README.md target/doitincloud.rdbcache
cp -r src/install/* target/doitincloud.rdbcache

cd target

#tar --exclude=.DS_Store --exclude=.* -zcf doitincloud.rdbcache.tar.gz doitincloud.rdbcache
#cp -f doitincloud.rdbcache.tar.gz download/

zip doitincloud.rdbcache.zip doitincloud.rdbcache/*
cp -f doitincloud.rdbcache.zip ../download/

cd ..

git add .

git commit -m "update build"

git push
